version: "1.0.0"
services:
  go-course-web:
    platform: linux/amd64
    container_name: go_course
    build: 
      context: ./.docker/mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_course_web
    ports:
    - "3320:3306"
    volumes:
      - ./.docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql